str(b'Zoot!')
str.capitalize()
str.casefold()
str.center(width[, fillchar])
str.count(sub[, start[, end]])
str.encode(encoding="utf-8", errors="strict")
str.endswith(suffix[, start[, end]])
str.expandtabs(tabsize=8)
str.find(sub[, start[, end]])
str.format(*args, **kwargs)
str.format_map(mapping)
str.index(sub[, start[, end]])
str.isalnum()
str.isalpha()
str.isascii()
str.isdecimal()
str.isdigit()
str.isidentifier()
str.islower()
str.isnumeric()
str.isprintable()
str.isspace()
str.istitle()
str.isupper()
str.join(iterable)
str.ljust(width[, fillchar])
str.lower()
str.lstrip([chars])
str.maketrans(x[, y[, z]])
str.partition(sep)
str.replace(old, new[, count])
str.rfind(sub[, start[, end]])
str.rindex(sub[, start[, end]])
str.rjust(width[, fillchar])
str.rpartition(sep)
str.rsplit(sep=None, maxsplit=-1)
str.rstrip([chars])
str.split(sep=None, maxsplit=-1)
str.splitlines([keepends])
str.startswith(prefix[, start[, end]])
str.strip([chars])
str.swapcase()
str.title()
str.translate(table)
str.upper()
str.zfill(width)

int([x])
int(x, base=10)
isinstance(object, classinfo)
issubclass(class, classinfo)
iter(object[, sentinel])
id(object)

len(s)
list([iterable])
locals()

map(function, iterable, ...)
max(iterable, *[, key, default])
max(arg1, arg2, *args[, key])
memoryview(obj)
min(iterable, *[, key, default])
min(arg1, arg2, *args[, key])

next(iterator[, default])

object
oct(x)
bin(x)
hex(x)

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
ord(c)

pow(x, y[, z])
print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)
property(fget=None, fset=None, fdel=None, doc=None)

range(stop)
range(start, stop[, step])
repr(object)
reversed(seq)
round(number[, ndigits])

set([iterable])
setattr(object, name, value)
slice(stop)
slice(start, stop[, step])
sorted(iterable, *, key=None, reverse=False)
staticmethod
sum(iterable[, start])
super([type[, object-or-type]])

tuple([iterable])
type(object)
type(name, bases, dict)

vars([object])
zip(*iterables)

id(object)
input([prompt])
print(bin(11))
